#!/usr/bin/env sh

# 1 option works with Lunix or Luniz like OS
# . "$(dirname -- "$0")/_/husky.sh"
# exec < /dev/tty && node_modules/.bin/cz --hook || true

# 2 option works fine but cmd window is popping out instead running on vscode 
#!/usr/bin/env sh
# // if we hve a cmd that is rinning npx cz that means finalize and commit
FILE=commit.cmd
if test -f "$FILE"; then
    echo "$FILE exists."
    rm commit.cmd
    exit 0;
fi
#// if on Windows, spwan a cmd that will run npx cz
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        echo "npx cz && exit" > commit.cmd
        start commit.cmd
    exit 1;;
esac
. "$(dirname "$0")/_/husky.sh"
exec < /dev/tty && node_modules/.bin/cz --hook || true

