export const teamList = [
   {
      id: 1,
      image: "/ourTeam/Anarkin.jpg",
      name: "Anarkin",
      instrument: "Вокал",
      orientation: "PORTRAIT",
      video: "/ourTeam/Anarkin.mp4",
      bluer: "",
   },
   {
      id: 2,
      image: "/ourTeam/Erbol.jpg",
      name: "Эрбол",
      instrument: "Гитара",
      orientation: "PORTRAIT",
      video: "/ourTeam/Erbol.mp4",
      bluer: "",
   },
   {
      id: 3,
      image: "/ourTeam/Suliko.jpg",
      name: "Сулико",
      instrument: "Бас-Гитара/Вокал",
      orientation: "PORTRAIT",
      video: "/ourTeam/Suliko.mp4",
      bluer: "",
   },
   {
      id: 4,
      image: "/ourTeam/Davlet.jpg",
      name: "Давлет",
      instrument: "Барабаны",
      orientation: "PORTRAIT",
      video: "/ourTeam/Davlet.mp4",
      bluer: "",
   },
   {
      id: 5,
      image: "/ourTeam/Osmany.jpg",
      name: "Османи",
      instrument: "Перкуссия/Вокал",
      orientation: "PORTRAIT",
      video: "/ourTeam/Osmany.mp4",
      bluer: "",
   },
   {
      id: 6,
      image: "/ourTeam/Dj Khan.jpg",
      name: "DJ Khan",
      instrument: "",
      orientation: "PORTRAIT",
      video: "/ourTeam/Dj Khan.mp4",
      bluer: "",
   },
   {
      id: 7,
      image: "/ourTeam/Dj Olymp.jpg",
      name: "DJ Olymp",
      instrument: "",
      orientation: "PORTRAIT",
      video: "/ourTeam/Dj Olymp.mp4",
      bluer: "",
   },
   {
      id: 8,
      image: "/ourTeam/Keno.jpg",
      name: "Keno",
      instrument: "Звукорежиссер",
      orientation: "PORTRAIT",
      video: "/ourTeam/Keno.mp4",
      bluer: "",
   },
   {
      id: 9,
      image: "/ourTeam/danceshow.jpg",
      name: "Dance Show",
      instrument: "",
      orientation: "LANDSCAPE",
      video: "/ourTeam/danceshow.mp4",
      bluer: "",
   },
];

const addAvailableVideo = teamList.map((el) => Object.assign(el));

export default addAvailableVideo;
